// src/shared/components/PageHeader/PageHeader.tsx
import type { ReactNode } from 'react'

export interface PageHeaderProps {
  title: string
  description?: string
  actions?: ReactNode
}

/**
 * Reusable page header with Sloty's Arabic-first hierarchy.
 *
 * Keep it lightweight so feature pages can decide which actions and summary
 * content belong near the heading.
 */
export function PageHeader({ title, description, actions }: PageHeaderProps) {
  return (
    <header className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
      <div className="space-y-2">
        <h1 className="text-2xl font-bold text-[var(--sloty-text-primary)]">
          {title}
        </h1>
        {description ? (
          <p className="text-sm leading-6 text-[var(--sloty-text-muted)]">
            {description}
          </p>
        ) : null}
      </div>
      {actions ? <div className="flex shrink-0 gap-2">{actions}</div> : null}
    </header>
  )
}

// src/app/shared/components/page-header/page-header.component.ts
import { Component, input } from '@angular/core';

/**
 * Reusable page title block.
 *
 * Feature pages can use this to present a consistent Arabic heading,
 * supporting text, and optional eyebrow without recreating layout markup.
 */
@Component({
  selector: 'app-page-header',
  templateUrl: './page-header.component.html'
})
export class PageHeaderComponent {
  readonly title = input.required<string>();
  readonly eyebrow = input<string>('');
  readonly description = input<string>('');
}

<header class="space-y-2">
  @if (eyebrow()) {
    <p class="text-sm font-bold text-[var(--sloty-primary)]">{{ eyebrow() }}</p>
  }

  <h1 class="text-2xl font-black leading-tight text-[var(--sloty-text)] sm:text-3xl">
    {{ title() }}
  </h1>

  @if (description()) {
    <p class="max-w-2xl text-sm leading-7 text-[var(--sloty-muted)] sm:text-base">
      {{ description() }}
    </p>
  }
</header>
